stages:
  raw_dataset_creation:
    cmd: python src/data/load_data.py --config=params.yaml
    deps:
    - src/data/load_data.py
    - data/external/winequality.csv
    outs:
    - data/raw/winequality.csv
  
  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/winequality_train.csv
    - data/processed/winequality_test.csv

  # model_train:
  #   cmd: python src/models/train_model.py --config=params.yaml
  #   deps:
  #   - data/processed/churn_train.csv
  #   - data/processed/churn_test.csv
  #   - src/models/train_model.py